version: '3.3'

services:
  db:
    container_name: database-dumbbell
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - "./database/data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  adminer:
    container_name: adminer-dumbbell
    image: adminer
    restart: always
    ports:
      - 8083:8080